name: Docker Distribution

on:
  push:
    tags:
      - "*"

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t openhab-yandex .
      - name: Docker tag ref
        run: docker tag openhab-yandex alexsergin/openhab-yandex:${GITHUB_REF#refs/tags/}
      - name: Docker tag latest
        run: docker tag openhab-yandex alexsergin/openhab-yandex:latest
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push tag
        run: docker push alexsergin/openhab-yandex:${GITHUB_REF#refs/tags/}
      - name: Docker push latest
        run: docker push alexsergin/openhab-yandex:latest
